eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
# ---------------------------
microservice:
  pospayment:
    endpoints:
      endpoint:
        uri: http://POSPAYMENT/payment/getPayment
  poscustomer:
    endpoints:
      endpoint:
        uri: http://POSCUSTOMER/customer/getCustomer
  posdelivery:
    endpoints:
      endpoint:
        uri: http://POSDELIVERY/delivery/getDelivery
  possale:
    endpoints:
      endpoint:
        uri: http://POSSALE/sale/getSale
  posstore:
    endpoints:
      endpoint:
        uri: http://POSSTORE/store/getStore
  possecurityserver:
    endpoints:
      endpoint:
        uri: http://POSSECURITYSERVER/login
      endpoint1:
        uri: http://POSSECURITYSERVER/speciallogout
      endpoint2:
        uri: http://POSSECURITYSERVER/user/getusers
      endpoint3:
        uri: http://POSSECURITYSERVER/user/save
      endpoint4:
        uri: http://POSSECURITYSERVER/role/getroles
      endpoint5:
        uri: http://POSSECURITYSERVER/role/save
      endpoint6:
        uri: http://POSSECURITYSERVER/role/addtouser
      endpoint7:
        uri: http://POSSECURITYSERVER/token/refreshToken
      endpoint8:
        uri: http://POSSECURITYSERVER/token/validateToken
# ---------------------------
